version: "3.1"
services:
  servidor_php:
    container_name: servidor_php_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html     
    restart: always  

